version: '3.8'

services:
  mcp-servers:
    build: .
    ports:
      - "3000:3000"  # Main HTTP server
      - "3001:3001"  # Sequential Thinking TCP proxy
      - "3002:3002"  # Puppeteer TCP proxy
      - "3003:3003"  # Memory Bank TCP proxy
      - "3004:3004"  # Playwright TCP proxy
      - "3005:3005"  # GitHub TCP proxy
      - "3006:3006"  # Knowledge Graph TCP proxy
      - "3007:3007"  # MCP Compass TCP proxy
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./logs:/app/logs
      - ./proxy-config.json:/app/proxy-config.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s